
name: CI

on:
  push:
    branches: [ master ]
    tags: [v*]
  pull_request:
    branches: [ master ]
   

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sunjia1
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfile
          push: true
          tags: sunjia1/test1:${{ secrets.MINOR }}
          
      - name: Exexute command
        uses: appleboy/ssh-action@master
        with:
          host: 49.234.22.25
          username: ubuntu
          key: ${{ secrets.SSHKEY }}
          port: 22
          script: |
            sudo docker images
            sudo docker stop $(sudo docker ps -aq)
            sudo docker pull sunjia1/test1
            sudo docker run -dp 3000:3000  sunjia1/test1:${{ secrets.MINOR }}
            sudo docker ps
            
      - name: Update Minor version
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'MINOR'
          value: $((${{ secrets.MINOR }}+1))
          repository: goc-Sunrujia1/docker_test
          token: ${{ secrets.REPO_ACCESS_TOKEN }}   
        
